---
dependency:
  name: galaxy
# driver:
#  name: docker
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu1804-zeek-role-tester
    box: ubuntu/bionic64
    cpus: 4
    memory: 8192
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
provisioner:
  name: ansible
  log: True
  #options:
    #v: True
    #vvv: True
  #privilege_escalation:
  #  become_flags: "-i"
  #config_options:
    #defaults:
    #  roles_path:
    #  library:
    #  filter_plugins:
  lint:
    name: ansible-lint
    options:
      x: [ANSIBLE0012, ANSIBLE0013]
verifier:
  name: testinfra
  lint:
    name: flake8
