---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s9:
      dhcp4: false

  bridges:
    {{ zeek_interface }}:
      dhcp4: true
      interfaces: [enp0s9]
      parameters:
        stp: false
        forward-delay: 0
