---

- name: Update APT package cache
  action: apt update_cache=yes cache_valid_time=600
  become: true

- name: run dist-upgrade
  become: true
  apt: upgrade=dist
  when: ansible_distribution == 'Ubuntu'

- name: Set time to {{ timezone }}
  become: true
  timezone:
    name: '{{ timezone }}'

- name: Install dependencies
  apt:
    name:
      - xz-utils
      - lsb-core
      - cmake
      - clang
      - make
      - doxygen
      - gcc
      - 'g++'
      - sendmail
      - gdb
      - git
      - librocksdb-dev
      - libreadline-dev
      - software-properties-common
      - flex
      - bison
      - libpcap-dev
      - libssl-dev
      - python-dev
      - python-pip
      - swig
      - zlib1g-dev
    state: present
    update_cache: true
  become: true

# create zeek user & set permissions
- name: Create Zeek user
  become: true
  user:
    name: '{{ zeek_user }}'
    shell: '/bin/bash'
    home: '/home/zeek'

- include: "pfring.yml"
  when: enable_pfring
- include: "networking.yml"
- include: "geoip.yml"
- include: "install_src.yml"
- include: "configure_zeek.yml"
- include: "zeek_scripts.yml"
- include: "zeek_packages.yml"

- name: "sync fs"
  shell: sync
  become: true
