---

- name: ensure pip is installed
  apt:
    name: python-pip
    state: present

- name: Set .zkg perms
  become: true
  file:
    path: '/home/{{ zeek_user }}/.zkg'
    owner: '{{ zeek_user }}'
    group: '{{ zeek_user }}'
    recurse: true

- name: ensure zkg directory
  become: true
  file:
    state: directory
    path:  '{{ item }}'
    owner: '{{ zeek_user }}'
    group: '{{ zeek_user }}'
  with_items:
    - /home/zeek/.zkg

- name: install zeek package manager
  become: true
  pip:
    name: zkg
    state: present
    executable: /usr/bin/pip

#- name: stat zkg config
  #stat:
    #path: /home/zeek/.zkg/config
  #register: zkg_cfg

#- name: create zkg config file
  #become: true
  #become_user: '{{ zeek_user }}'
  #become_flags: '-i'
  #become_method: 'sudo'
  #shell: zkg autoconfig

- name: drop zkg config
  become: true
  template:
    src: zkg_config.j2
    dest: '/home/{{ zeek_user }}/.zkg/config'
    force: true
    trim_blocks: false

- name: dump config
  shell: cat /home/zeek/.zkg/config
  register: cfg

- name: 'zkg config'
  debug: 
    var: cfg
    verbosity: 3

- name: add load packages directive to local.zeek
  become: true
  lineinfile:
    path: '{{ zeek_base }}/share/zeek/site/local.zeek'
    line: '{{ item }}'
  with_items:
    - '# load zeek packages'
    - '@load packages'

- include: "setcaps.yml"

- name: stop zeek
  shell: '{{ zeek_base }}/bin/zeekctl stop'
  become: true
  become_user: '{{ zeek_user }}'
  become_flags: '-i'

- name: install packages
  shell: 'zkg install --force {{ item }}'
  become: true
  become_flags: '-i'
  become_user: '{{ zeek_user }}'
  with_items: '{{ zkg_install_packages }}'

- include: "setcaps.yml"

- name: run zeek deploy & status
  become: true
  become_flags: '-i'
  become_user: '{{ zeek_user }}'
  shell: '{{ zeek_base }}/bin/zeekctl {{ item }}'
  with_items:
    - 'deploy'
    - 'status'
